# Packaging environments
bionic:
  build: ./packagingenv/bionic
  extends:
    file: docker-compose.override.yml
    service: suite

focal:
  build: ./packagingenv/focal
  extends:
    file: docker-compose.override.yml
    service: suite

el8:
  build: ./packagingenv/rockylinux8
  extends:
    file: docker-compose.override.yml
    service: suite

el7:
  build: ./packagingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite

# Testing environments
bionic-test:
  build: ./testingenv/bionic
  extends:
    file: docker-compose.override.yml
    service: suite-test

focal-test:
  build: ./testingenv/focal
  extends:
    file: docker-compose.override.yml
    service: suite-test

el8-test:
  build: ./testingenv/rockylinux8
  extends:
    file: docker-compose.override.yml
    service: suite-test

el7-test:
  build: ./testingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite-test
