# Packaging environments
trusty:
  build: ./packagingenv/trusty
  extends:
    file: docker-compose.override.yml
    service: suite

xenial:
  build: ./packagingenv/xenial
  extends:
    file: docker-compose.override.yml
    service: suite

bionic:
  build: ./packagingenv/bionic
  extends:
    file: docker-compose.override.yml
    service: suite

el8:
  build: ./packagingenv/centos8
  extends:
    file: docker-compose.override.yml
    service: suite

el7:
  build: ./packagingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite

el6:
  build: ./packagingenv/centos6
  extends:
    file: docker-compose.override.yml
    service: suite

# Testing environments
trusty-test:
  build: ./testingenv/trusty
  extends:
    file: docker-compose.override.yml
    service: suite-test

xenial-test:
  build: ./testingenv/xenial
  extends:
    file: docker-compose.override.yml
    service: suite-test

bionic-test:
  build: ./testingenv/bionic
  extends:
    file: docker-compose.override.yml
    service: suite-test

el8-test:
  build: ./testingenv/centos8
  extends:
    file: docker-compose.override.yml
    service: suite-test

el7-test:
  build: ./testingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite-test

el6-test:
  build: ./testingenv/centos6
  extends:
    file: docker-compose.override.yml
    service: suite-test
