# Packaging environments
focal:
  build: ./packagingenv/focal
  extends:
    file: docker-compose.override.yml
    service: suite

el8:
  build: ./packagingenv/rockylinux8
  extends:
    file: docker-compose.override.yml
    service: suite

# Testing environments
focal-test:
  build: ./testingenv/focal
  extends:
    file: docker-compose.override.yml
    service: suite-test

el8-test:
  build: ./testingenv/rockylinux8
  extends:
    file: docker-compose.override.yml
    service: suite-test

